# Generated by Django 2.0.6 on 2018-08-03 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('feedbacks', '0002_auto_20180803_1406'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('student', 'teacher')},
        ),
    ]
