# Generated by Django 2.0.6 on 2018-08-03 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('feedbacks', '0003_auto_20180803_1407'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('student', 'teacher'), ('student', 'subject')},
        ),
    ]
