# Generated by Django 2.0.6 on 2018-08-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0004_auto_20180803_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ManyToManyField(to='feedbacks.Teacher'),
        ),
    ]
