# Generated by Django 2.0.6 on 2018-08-04 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0007_auto_20180804_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ManyToManyField(related_name='subjects', to='feedbacks.Teacher'),
        ),
    ]
