# Generated by Django 2.0.6 on 2018-08-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0009_auto_20180804_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='total',
            field=models.PositiveIntegerField(),
        ),
    ]
